### ISSUE TITLE
Training and evaluation of autoregressive / GPT-style language models

### ISSUE THREAD

**Issue by marksverdhei** [ltgoslo/norbench#34]
Hi!

I'm currently researching open LLMs for Norwegian, and since a lot of SOTA solutions nowadays are based on scaling up
GPT-style causal LM models and fine-tune them on instructions, I think it would make sense to have 
some evaluation and fine-tuning scripts and metrics for these types of models too. 

I've already made a fork where I'm working on this myself, but I'm wondering:
1. Is this something that is already being looked into?
2. If not, could a contribution to this main repo be desirable?

**Comment by akutuzov** [comment]
Hi,

As you can see, we already have some benchmarks for generative models (and even a [leaderboard](https://github.com/ltgoslo/norbench/blob/main/t5_leaderboard.md)).  It currently features only encoder-decoder models, but it should be pretty straightforward to run the same evaluations for decode-only models (GPT-like) as well.

If you would like to contribute to testing the applicability of the existing scripts to the causal models, this will be very welcome, thanks!

**Comment by marksverdhei** [comment]
Thanks.
I was aware of the scripts for training generative models, but from a quick glance, 
I could tell that they would need alterations (though probably quite small) to work with causal lm models.
