### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by marksverdhei** [ltgoslo/norbench#35]
Hi!
Was just wondering if there's any open-source license that applies to the code in the repo
or if it was a conscious decision to leave one out. 
I understand that different licenses apply to the different datasets in the repo. Perhaps it could be listed in the readme?
It would be nice to know what we can and can't do with the code

**Comment by akutuzov** [comment]
Thanks for noticing!
The code is released under the MIT license (added to the repository now).

The datasets are published under their own licenses and you should refer to their respective authors (and respective repositories).
