### ISSUE TITLE
XLM-R model for tasks in the NorBench

### ISSUE THREAD

**Issue by sigdelina** [ltgoslo/norbench#4]
The current issue provides the information about implementing XLM-R for the tasks mentioned below:

1. Part-of-Speech tagging Bokmål
2. Part-of-Speech tagging Nynorsk
3. Binary sentiment analysis
4. Named entity recognition Bokmål
5. Named entity recognition Nynorsk

**Comment by sigdelina** [comment]
1. The [first attempt ](https://github.com/sigdelina/NorBench/tree/main/XLM-R%20model/pos/experiments) to run XLM-R model for POS-tagging task was successfully launched.

2. The task that is currently in the process is to integrate the code from the first attempt into the [original script](https://github.com/ltgoslo/NorBERT/tree/main/benchmarking/experiments)

**Comment by sigdelina** [comment]
-  The launch of the `xlm-roberta-base` from the original script was successful. Scores for Bokmål and Nyrnorsk POS-tagging task can be found [here](https://github.com/sigdelina/NorBench/tree/main/original_code_norbench).

#### Next steps:
1. The next step is to make the script more flexible and provide the selection of the model and tokenizer automatically (in progress)
2. Implementing XLM-R model for sentiment task

**Comment by sigdelina** [comment]
- The launch of the `xlm-roberta-base` from the original script was successful. Scores for Sentiment analysis task can be found [here](https://github.com/sigdelina/NorBench/tree/main/original_code_norbench) as well.

#### Next steps:

1. The next step is to make the script more flexible and provide the selection of the model and tokenizer automatically (in progress)
2. Implementing XLM-R model for Named entity recognition task

**Comment by akutuzov** [comment]
Thanks, waiting for the NER results.
